"""empty message

Revision ID: 9412efa5a4d0
Revises: 
Create Date: 2024-01-22 15:13:45.784654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9412efa5a4d0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.drop_index('auth_permission_content_type_id_codename_01ab375a_uniq')

    op.drop_table('auth_permission')
    op.drop_table('fair_price_segment')
    op.drop_table('weighted_economic_sector')
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.drop_index('auth_user_groups_user_id_group_id_94350c0c_uniq')

    op.drop_table('auth_user_groups')
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('auth_user')
    with op.batch_alter_table('socialaccount_socialapp_sites', schema=None) as batch_op:
        batch_op.drop_index('socialaccount_socialapp_sites_socialapp_id_site_id_71a9a768_uniq')

    op.drop_table('socialaccount_socialapp_sites')
    op.drop_table('apps_ticketlist')
    with op.batch_alter_table('socialaccount_socialaccount', schema=None) as batch_op:
        batch_op.drop_index('socialaccount_socialaccount_provider_uid_fc810c6e_uniq')

    op.drop_table('socialaccount_socialaccount')
    with op.batch_alter_table('account_emailaddress', schema=None) as batch_op:
        batch_op.drop_index('account_emailaddress_upper')
        batch_op.drop_index('account_emailaddress_user_id_email_987c8728_uniq')

    op.drop_table('account_emailaddress')
    op.drop_table('apps_jobapplication')
    with op.batch_alter_table('apps_crmcompany', schema=None) as batch_op:
        batch_op.drop_index('contact_email')

    op.drop_table('apps_crmcompany')
    op.drop_table('fair_price_stock')
    with op.batch_alter_table('django_site', schema=None) as batch_op:
        batch_op.drop_index('django_site_domain_a2e37b91_uniq')

    op.drop_table('django_site')
    with op.batch_alter_table('account_emailconfirmation', schema=None) as batch_op:
        batch_op.drop_index('key')

    op.drop_table('account_emailconfirmation')
    with op.batch_alter_table('apps_ecommercecustomer', schema=None) as batch_op:
        batch_op.drop_index('email_id')

    op.drop_table('apps_ecommercecustomer')
    op.drop_table('fair_price_subsector')
    with op.batch_alter_table('apps_crmcontact', schema=None) as batch_op:
        batch_op.drop_index('email_id')

    op.drop_table('apps_crmcontact')
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq')

    op.drop_table('auth_group_permissions')
    op.drop_table('apps_crmlead')
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.drop_index('django_content_type_app_label_model_76bd3d3b_uniq')

    op.drop_table('django_content_type')
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.drop_index('django_session_expire_date_a5c62663')

    op.drop_table('django_session')
    op.drop_table('django_migrations')
    op.drop_table('fair_price_B3')
    with op.batch_alter_table('socialaccount_socialtoken', schema=None) as batch_op:
        batch_op.drop_index('socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq')

    op.drop_table('socialaccount_socialtoken')
    op.drop_table('brapi_API_data_fund_ind_2023_Q3')
    op.drop_table('weighted_segment')
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.drop_index('user_id')

    op.drop_table('user_images')
    op.drop_table('brapi_API_data_daily')
    op.drop_table('socialaccount_socialapp')
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.drop_index('name')

    op.drop_table('auth_group')
    op.drop_table('brapi_API_data_price_ind')
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.drop_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq')

    op.drop_table('auth_user_user_permissions')
    op.drop_table('apps_ecommerceorder')
    op.drop_table('weighted_subsector')
    op.drop_table('django_admin_log')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    op.create_table('django_admin_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('action_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('object_id', mysql.LONGTEXT(), nullable=True),
    sa.Column('object_repr', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('action_flag', mysql.SMALLINT(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('change_message', mysql.LONGTEXT(), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`action_flag` >= 0)', name='django_admin_log_chk_1'),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='django_admin_log_content_type_id_c4bce8eb_fk_django_co'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='django_admin_log_user_id_c564eba6_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('weighted_subsector',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('weighted_mean_currentPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardPE', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceToBook', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_pegRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetHighPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetLowPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMeanPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMedianPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_quickRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_currentRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_debtToEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenuePerShare', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnAssets', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenueGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_grossMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_ebitdaMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_operatingMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_profitMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_beta', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_bookValue', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsQuarterlyGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_trailingEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbitda', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbit', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_dividendYield', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apps_ecommerceorder',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('product', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('order_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('amount', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_user_user_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_user_user_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_user_user_permissions_user_id_permission_id_14a6b632_uniq', ['user_id', 'permission_id'], unique=True)

    op.create_table('brapi_API_data_price_ind',
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('marketCap', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('currentPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('priceEarnings', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('forwardPE', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('priceToBook', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('pegRatio', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('targetHighPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('targetLowPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('targetMeanPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('targetMedianPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('numberOfAnalystOpinions', mysql.INTEGER(), autoincrement=False, nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group', schema=None) as batch_op:
        batch_op.create_index('name', ['name'], unique=True)

    op.create_table('socialaccount_socialapp',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=30), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('client_id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('secret', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('key', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('provider_id', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('settings', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('brapi_API_data_daily',
    sa.Column('Ação', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('P/L', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('LPA trailing', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('LPA forward', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('P/VPA', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('VPA', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_images',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_image', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_images_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user_images', schema=None) as batch_op:
        batch_op.create_index('user_id', ['user_id'], unique=True)

    op.create_table('weighted_segment',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('weighted_mean_currentPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardPE', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceToBook', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_pegRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetHighPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetLowPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMeanPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMedianPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_quickRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_currentRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_debtToEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenuePerShare', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnAssets', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenueGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_grossMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_ebitdaMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_operatingMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_profitMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_beta', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_bookValue', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsQuarterlyGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_trailingEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbitda', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbit', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_dividendYield', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('brapi_API_data_fund_ind_2023_Q3',
    sa.Column('symbol', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('quickRatio', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('currentRatio', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('debtToEquity', mysql.FLOAT(), nullable=True),
    sa.Column('revenuePerShare', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('returnOnAssets', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('returnOnEquity', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('earningsGrowth', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('revenueGrowth', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('grossMargins', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('ebitdaMargins', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('operatingMargins', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('profitMargins', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('heldPercentInsiders', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('heldPercentInstitutions', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('beta', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('bookValue', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('earningsQuarterlyGrowth', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('trailingEps', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('forwardEps', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('enterpriseToEbitda', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('enterpriseToEbit', mysql.DECIMAL(precision=4, scale=2), nullable=True),
    sa.Column('dividendYield', mysql.DECIMAL(precision=4, scale=3), nullable=True),
    sa.Column('economicSector', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('subSector', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('segment', mysql.VARCHAR(length=100), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('socialaccount_socialtoken',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', mysql.LONGTEXT(), nullable=False),
    sa.Column('token_secret', mysql.LONGTEXT(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('account_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('app_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['socialaccount_socialaccount.id'], name='socialaccount_social_account_id_951f210e_fk_socialacc'),
    sa.ForeignKeyConstraint(['app_id'], ['socialaccount_socialapp.id'], name='socialaccount_social_app_id_636a42d7_fk_socialacc'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('socialaccount_socialtoken', schema=None) as batch_op:
        batch_op.create_index('socialaccount_socialtoken_app_id_account_id_fca4e0ac_uniq', ['app_id', 'account_id'], unique=True)

    op.create_table('fair_price_B3',
    sa.Column('b3', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('marketCap', mysql.DECIMAL(precision=50, scale=2), nullable=True),
    sa.Column('currentPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fairPrice_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('fairPrice_priceEarningsForward', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_migrations',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('app', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('applied', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('django_session',
    sa.Column('session_key', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('session_data', mysql.LONGTEXT(), nullable=False),
    sa.Column('expire_date', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('session_key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_session', schema=None) as batch_op:
        batch_op.create_index('django_session_expire_date_a5c62663', ['expire_date'], unique=False)

    op.create_table('django_content_type',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('app_label', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('model', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_content_type', schema=None) as batch_op:
        batch_op.create_index('django_content_type_app_label_model_76bd3d3b_uniq', ['app_label', 'model'], unique=True)

    op.create_table('apps_crmlead',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('profile_pic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('lead_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('tags', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('create_date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_group_permissions',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_group_permissions_group_id_b120cbf9_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['permission_id'], ['auth_permission.id'], name='auth_group_permissio_permission_id_84c5c92e_fk_auth_perm'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_group_permissions', schema=None) as batch_op:
        batch_op.create_index('auth_group_permissions_group_id_permission_id_0cd325b0_uniq', ['group_id', 'permission_id'], unique=True)

    op.create_table('apps_crmcontact',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('profile_pic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('company_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('lead_score', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tags', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apps_crmcontact', schema=None) as batch_op:
        batch_op.create_index('email_id', ['email_id'], unique=True)

    op.create_table('fair_price_subsector',
    sa.Column('subSector', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('marketCap', mysql.DECIMAL(precision=50, scale=2), nullable=True),
    sa.Column('currentPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fairPrice_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('fairPrice_priceEarningsForward', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apps_ecommercecustomer',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('joining_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apps_ecommercecustomer', schema=None) as batch_op:
        batch_op.create_index('email_id', ['email_id'], unique=True)

    op.create_table('account_emailconfirmation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('sent', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('key', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email_address_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['email_address_id'], ['account_emailaddress.id'], name='account_emailconfirm_email_address_id_5b7f8c58_fk_account_e'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('account_emailconfirmation', schema=None) as batch_op:
        batch_op.create_index('key', ['key'], unique=True)

    op.create_table('django_site',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('django_site', schema=None) as batch_op:
        batch_op.create_index('django_site_domain_a2e37b91_uniq', ['domain'], unique=True)

    op.create_table('fair_price_stock',
    sa.Column('symbol', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('marketCap', mysql.DECIMAL(precision=50, scale=2), nullable=True),
    sa.Column('currentPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fairPrice_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('fairPrice_priceEarningsForward', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('apps_crmcompany',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('logo', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('owner_name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('industry_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('rating', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('employee', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('website', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('contact_email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('since', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apps_crmcompany', schema=None) as batch_op:
        batch_op.create_index('contact_email', ['contact_email'], unique=True)

    op.create_table('apps_jobapplication',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('profile_pic', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('company_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('apply_date', sa.DATE(), nullable=False),
    sa.Column('contact', mysql.VARCHAR(length=13), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('account_emailaddress',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('verified', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('primary', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='account_emailaddress_user_id_2c513194_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('account_emailaddress', schema=None) as batch_op:
        batch_op.create_index('account_emailaddress_user_id_email_987c8728_uniq', ['user_id', 'email'], unique=True)
        batch_op.create_index('account_emailaddress_upper', [], unique=False)

    op.create_table('socialaccount_socialaccount',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('uid', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('extra_data', mysql.JSON(), nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='socialaccount_socialaccount_user_id_8146e70c_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('socialaccount_socialaccount', schema=None) as batch_op:
        batch_op.create_index('socialaccount_socialaccount_provider_uid_fc810c6e_uniq', ['provider', 'uid'], unique=True)

    op.create_table('apps_ticketlist',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('client_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('assign_to', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('create_date', sa.DATE(), nullable=False),
    sa.Column('due_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('priority', mysql.VARCHAR(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('socialaccount_socialapp_sites',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('socialapp_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('site_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['django_site.id'], name='socialaccount_socialapp_sites_site_id_2579dee5_fk_django_site_id'),
    sa.ForeignKeyConstraint(['socialapp_id'], ['socialaccount_socialapp.id'], name='socialaccount_social_socialapp_id_97fb6e7d_fk_socialacc'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('socialaccount_socialapp_sites', schema=None) as batch_op:
        batch_op.create_index('socialaccount_socialapp_sites_socialapp_id_site_id_71a9a768_uniq', ['socialapp_id', 'site_id'], unique=True)

    op.create_table('auth_user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('password', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('last_login', mysql.DATETIME(fsp=6), nullable=True),
    sa.Column('is_superuser', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=254), nullable=False),
    sa.Column('is_staff', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('date_joined', mysql.DATETIME(fsp=6), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_user', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.create_table('auth_user_groups',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('group_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['auth_group.id'], name='auth_user_groups_group_id_97559544_fk_auth_group_id'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='auth_user_groups_user_id_6a12ed8b_fk_auth_user_id'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_user_groups', schema=None) as batch_op:
        batch_op.create_index('auth_user_groups_user_id_group_id_94350c0c_uniq', ['user_id', 'group_id'], unique=True)

    op.create_table('weighted_economic_sector',
    sa.Column('key', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('weighted_mean_currentPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardPE', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_priceToBook', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_pegRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetHighPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetLowPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMeanPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_targetMedianPrice', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_quickRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_currentRatio', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_debtToEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenuePerShare', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnAssets', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_returnOnEquity', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_revenueGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_grossMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_ebitdaMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_operatingMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_profitMargins', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_beta', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_bookValue', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_earningsQuarterlyGrowth', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_trailingEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_forwardEps', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbitda', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_enterpriseToEbit', mysql.FLOAT(), nullable=True),
    sa.Column('weighted_mean_dividendYield', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fair_price_segment',
    sa.Column('segment', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('marketCap', mysql.DECIMAL(precision=50, scale=2), nullable=True),
    sa.Column('currentPrice', mysql.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('fairPrice_priceEarnings', mysql.FLOAT(), nullable=True),
    sa.Column('fairPrice_priceEarningsForward', mysql.FLOAT(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('auth_permission',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('content_type_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codename', mysql.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['content_type_id'], ['django_content_type.id'], name='auth_permission_content_type_id_2f476e4b_fk_django_co'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('auth_permission', schema=None) as batch_op:
        batch_op.create_index('auth_permission_content_type_id_codename_01ab375a_uniq', ['content_type_id', 'codename'], unique=True)

    # ### end Alembic commands ###
